---
name: JSON Lint
description: A Buildkite plugin to check JSON files and syntax errors
author: https://msha.ke/johnsyweb/
requirements:
  - docker
configuration:
  properties:
    pattern:
      type: string
    version:
      type: string
