#!/bin/bash
set -euo pipefail

PATTERN="${BUILDKITE_PLUGIN_JSONLINT_PATTERN:-*.*json}"
JSONLINT_VERSION="${BUILDKITE_PLUGIN_JSONLINT_VERSION:-latest}"

echo "--- :json: checking JSON files (${PATTERN})..."

errors=0
while IFS= read -r -d '' jsonfile
do
    docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "cytopia/jsonlint:${JSONLINT_VERSION}" "${jsonfile}" || errors=1
done < <(find . -name  "${PATTERN}" -print0)

if [[ ${errors} -lt 1 ]]
then
    echo "Beautiful!"
else
    echo "Mistakes were made."
fi

exit ${errors}
